-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguD3qmTirqfJ4W7zI
4F8st+dtSthVe++Uj5nDfPp9bCugCgYIKoZIzj0DAQehRANCAARUQ/sXvboeanwf
URto15L00wxi9U8myHyhDLfQXjLD4YgDwgXGI9k6al8Oa/WR9TUwqyqvF+to+pqr
sG9aV4Ef
-----END PRIVATE KEY-----